apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic-logging
  namespace: newrelic-logging
spec:
  releaseName: newrelic-logging
  chart:
    spec:
      chart: newrelic-logging
      sourceRef:
        kind: HelmRepository
        name: newrelic
        namespace: flux-system
      version: "1.4.8"
  interval: 5m
  # Default values
  # https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-logging/values.yaml
  valuesFrom:
  - kind: Secret
    name: newrelic-logging-values
