apiVersion: v1
kind: Secret
metadata:
    name: newrelic-logging
stringData:
    values.yaml:
        licenseKey: ENC[AES256_GCM,data:Cyia9eoI0gO6lZnObalfMYjn/JPllgyuzOqgaCcThAX1HSBjy9ndbg==,iv:JJogVk0oIxeDsuxkyyjTJ/dpBD/AZ2PylcYB2IS2iQw=,tag:09U79Q7HLsbLzP5NyQF+CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-28T08:16:40Z"
    mac: ENC[AES256_GCM,data:TASam0FsnktnDusi+cHtIo1v/0pN46ytumpCpDulnAW+ybdxi+tMqr8fSzDkA20Z8rga0y+Xzxz6B+hJemYdQTMOmQlmtA29Hdp62c6Q2W1R68+X1K57tka+2acrwP45qRuem9P4wgpnMGHKbjrpphBZdBaJLI+X+SnLiT/ovDg=,iv:JaTe+IwJoEq0yCEAFRGLgjnnIN6MrTQHSH1gnoFa5cw=,tag:4Kqd7tLlxLJxVd47HZ1CjQ==,type:str]
    pgp:
        - created_at: "2021-05-28T08:01:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzCmaKGKv3neAQ/+OXw+zZnsit8tJiYJ+W4I+C2VO0BxXT65Oqj7FmjpY6uc
            vLQMjj5IUg1VdHRO6RNNis1SMkKszNvKyXivLX/g8Nt8QNSE26NQH2vtIouTKssm
            x62zUmoSoSy0v26fu55BJpvlinfUWgD2pamgFbVTcSCI/3zmbte8uoGoB/ISGp9n
            RFFpus87o+qIhVREXE4hzZrDYCYV3O4gA5KNp/FpJEQM0VsCBj6joRtZMpmUasBs
            iOsrVOMN+4v4+eL0Kmqu3EBRBcvztrklUNrYzKijVq3tZLLi2rAkTVUfYkC8rJJv
            Pm3YX6l32PLGx/C6gC5HzGDhM4z4aFtcJZsr5N1mztmBhEW0whBAXt7rofL04An+
            PiWbiisub0K1klwDKHs24cZqPv2ITBE/L7iwjZICspSN7h2iIWoxdMjtpld32pXg
            I5VQYRovcssurAhCsSwgh9L2yL5jlTnJ+lf4fPyPRMUDBj0ln80yrjeNaWidhBXe
            pV4ppiXpKdCMMcu6gG6vCefszoSr/NSpESIcOAT0C6w9jDo8rwNqvk9mq63LVGW+
            T5uXnkdMK6IjlWayPkcjdf25YxvB166u918++Uo+bKi0G7v1XH/fuo3EjIQVNLbI
            pPGVK8V6DYQ/6qvLbzhY+ZEXy9EP4DUEhFLcta2EiKgXS5dNJlkRh2vLiocNRFrS
            XgEM3C4bxpHqR54/mYomwAiHali7a0wmjla6GQsPEYwcVmRylV+T+xBVIHARVdzN
            G969v8ryD5Z6fctYHvwEEpnWVLGSEXgXJOi2mQwHdCoAcpTcBBAaP3TgW0D+pok=
            =+vlX
            -----END PGP MESSAGE-----
          fp: 4D7E5EA804E21305AF4EF94352786FEE3C60E785
    encrypted_regex: ^(licenseKey)$
    version: 3.7.1
